'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { ExampleInput as ExampleInputElement, defineCustomElement as defineExampleInput } from "@example/stencil-lib/dist/components/example-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ExampleInputEvents = {
    onExampleChange: EventName<CustomEvent<string>>,
    onExampleFocus: EventName<CustomEvent<void>>,
    onExampleBlur: EventName<CustomEvent<void>>
};

export const ExampleInput: StencilReactComponent<ExampleInputElement, ExampleInputEvents> = /*@__PURE__*/ createComponent<ExampleInputElement, ExampleInputEvents>({
    tagName: 'example-input',
    elementClass: ExampleInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onExampleChange: 'exampleChange',
        onExampleFocus: 'exampleFocus',
        onExampleBlur: 'exampleBlur'
    } as ExampleInputEvents,
    defineCustomElement: defineExampleInput
});
